name: api_todo
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  alfred: ^1.1.1
  args: ^2.4.0
  corsac_jwt: ^1.0.0-nullsafety.1
  get_it: ^7.6.8
  json_annotation: ^4.8.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  json_serializable: ^6.7.1
